[k8snode-01]
   uuid = "31D7ADDF-96D7-428A-A17F-14CB902CCD05"
   channel = "stable"
   volume = "node-01-data.img"
   cloud_config = "cloud-init/user-data.node1"
   cpus = 2
   memory = 2048
   local = "true"
   offline = "true"

